using System.Collections.Generic;
using System.Linq;
using WindowsInput.Native;

namespace CircleInput2
{
    class KeyCode
    {
        /* 以下は256以上を指定する必要がある */
        // 特殊キー
        public enum CircleVirtualKey
        {
            ///// 特殊キー /////
            V_KEY_NOTHING = 256, // なにもしない
            V_KEY_FN,      // ファンクションキー
            V_KEY_UNE_BS,  // 日本語の子音指定のキャンセル、BackSpace TODO
            V_KEY_IN_ENT,  // 日本語の文字選択、Enter
            V_KEY_IN_NE,   // 日本語の文字選択、サブプリセット遷移
            V_KEY_SASS,    // Shift and Space TODO
            V_KEY_FN_BS,   // ファンクションキーまたは、BackSpace
            V_KEY_PRES,    // プリセットキー
            ///// ホイール制御キー /////
            V_KEY_MOUSE_X,
            V_KEY_MOUSE_Y,
            V_KEY_WHEEL_X,
            V_KEY_WHEEL_Y,
            V_KEY_SHIFT_WHEEL_X,
            V_KEY_SHIFT_WHEEL_Y,
            V_KEY_CTRL_WHEEL_X,
            V_KEY_CTRL_WHEEL_Y,
            V_KEY_SC_WHEEL_X,
            V_KEY_SC_WHEEL_Y,
            V_KEY_ALT_WHEEL_X,
            V_KEY_ALT_WHEEL_Y,
            V_KEY_CIRCLE
        }

        /// <summary>
        /// キーコードと別名を関連付ける
        /// </summary>
        public static Dictionary<string, int> dict = new Dictionary<string, int>()
        {
            {"LBUTTON",    (int) VirtualKeyCode.LBUTTON},
            {"RBUTTON",    (int) VirtualKeyCode.RBUTTON},
            {"CANCEL",     (int) VirtualKeyCode.CANCEL},
            {"MBUTTON",    (int) VirtualKeyCode.MBUTTON},
            {"XBUTTON1",   (int) VirtualKeyCode.XBUTTON1},
            {"XBUTTON2",   (int) VirtualKeyCode.XBUTTON2},
            {"BACK",       (int) VirtualKeyCode.BACK},
            {"TAB",        (int) VirtualKeyCode.TAB},
            {"CLEAR",      (int) VirtualKeyCode.CLEAR},
            {"RETURN",     (int) VirtualKeyCode.RETURN},
            {"SHIFT",      (int) VirtualKeyCode.SHIFT},
            {"CONTROL",    (int) VirtualKeyCode.CONTROL},
            {"MENU",       (int) VirtualKeyCode.MENU},
            {"PAUSE",      (int) VirtualKeyCode.PAUSE},
            {"CAPITAL",    (int) VirtualKeyCode.CAPITAL},
            {"KANA",       (int) VirtualKeyCode.KANA},
            {"HANGEUL",    (int) VirtualKeyCode.HANGEUL},
            {"HANGUL",     (int) VirtualKeyCode.HANGUL},
            {"JUNJA",      (int) VirtualKeyCode.JUNJA},
            {"FINAL",      (int) VirtualKeyCode.FINAL},
            {"HANJA",      (int) VirtualKeyCode.HANJA},
            {"KANJI",      (int) VirtualKeyCode.KANJI},
            {"ESCAPE",     (int) VirtualKeyCode.ESCAPE},
            {"CONVERT",    (int) VirtualKeyCode.CONVERT},
            {"NONCONVERT", (int) VirtualKeyCode.NONCONVERT},
            {"ACCEPT",     (int) VirtualKeyCode.ACCEPT},
            {"MODECHANGE", (int) VirtualKeyCode.MODECHANGE},
            {"SPACE",      (int) VirtualKeyCode.SPACE},
            {"PRIOR",      (int) VirtualKeyCode.PRIOR},
            {"NEXT",       (int) VirtualKeyCode.NEXT},
            {"END",        (int) VirtualKeyCode.END},
            {"HOME",       (int) VirtualKeyCode.HOME},
            {"LEFT",       (int) VirtualKeyCode.LEFT},
            {"UP",         (int) VirtualKeyCode.UP},
            {"RIGHT",      (int) VirtualKeyCode.RIGHT},
            {"DOWN",       (int) VirtualKeyCode.DOWN},
            {"SELECT",     (int) VirtualKeyCode.SELECT},
            {"PRINT",      (int) VirtualKeyCode.PRINT},
            {"EXECUTE",    (int) VirtualKeyCode.EXECUTE},
            {"SNAPSHOT",   (int) VirtualKeyCode.SNAPSHOT},
            {"INSERT",     (int) VirtualKeyCode.INSERT},
            {"DELETE",     (int) VirtualKeyCode.DELETE},
            {"HELP",       (int) VirtualKeyCode.HELP},
            {"VK_0",       (int) VirtualKeyCode.VK_0},
            {"VK_1",       (int) VirtualKeyCode.VK_1},
            {"VK_2",       (int) VirtualKeyCode.VK_2},
            {"VK_3",       (int) VirtualKeyCode.VK_3},
            {"VK_4",       (int) VirtualKeyCode.VK_4},
            {"VK_5",       (int) VirtualKeyCode.VK_5},
            {"VK_6",       (int) VirtualKeyCode.VK_6},
            {"VK_7",       (int) VirtualKeyCode.VK_7},
            {"VK_8",       (int) VirtualKeyCode.VK_8},
            {"VK_9",       (int) VirtualKeyCode.VK_9},
            {"VK_A",       (int) VirtualKeyCode.VK_A},
            {"VK_B",       (int) VirtualKeyCode.VK_B},
            {"VK_C",       (int) VirtualKeyCode.VK_C},
            {"VK_D",       (int) VirtualKeyCode.VK_D},
            {"VK_E",       (int) VirtualKeyCode.VK_E},
            {"VK_F",       (int) VirtualKeyCode.VK_F},
            {"VK_G",       (int) VirtualKeyCode.VK_G},
            {"VK_H",       (int) VirtualKeyCode.VK_H},
            {"VK_I",       (int) VirtualKeyCode.VK_I},
            {"VK_J",       (int) VirtualKeyCode.VK_J},
            {"VK_K",       (int) VirtualKeyCode.VK_K},
            {"VK_L",       (int) VirtualKeyCode.VK_L},
            {"VK_M",       (int) VirtualKeyCode.VK_M},
            {"VK_N",       (int) VirtualKeyCode.VK_N},
            {"VK_O",       (int) VirtualKeyCode.VK_O},
            {"VK_P",       (int) VirtualKeyCode.VK_P},
            {"VK_Q",       (int) VirtualKeyCode.VK_Q},
            {"VK_R",       (int) VirtualKeyCode.VK_R},
            {"VK_S",       (int) VirtualKeyCode.VK_S},
            {"VK_T",       (int) VirtualKeyCode.VK_T},
            {"VK_U",       (int) VirtualKeyCode.VK_U},
            {"VK_V",       (int) VirtualKeyCode.VK_V},
            {"VK_W",       (int) VirtualKeyCode.VK_W},
            {"VK_X",       (int) VirtualKeyCode.VK_X},
            {"VK_Y",       (int) VirtualKeyCode.VK_Y},
            {"VK_Z",       (int) VirtualKeyCode.VK_Z},
            {"LWIN",       (int) VirtualKeyCode.LWIN},
            {"RWIN",       (int) VirtualKeyCode.RWIN},
            {"APPS",       (int) VirtualKeyCode.APPS},
            {"SLEEP",      (int) VirtualKeyCode.SLEEP},
            {"NUMPAD0",    (int) VirtualKeyCode.NUMPAD0},
            {"NUMPAD1",    (int) VirtualKeyCode.NUMPAD1},
            {"NUMPAD2",    (int) VirtualKeyCode.NUMPAD2},
            {"NUMPAD3",    (int) VirtualKeyCode.NUMPAD3},
            {"NUMPAD4",    (int) VirtualKeyCode.NUMPAD4},
            {"NUMPAD5",    (int) VirtualKeyCode.NUMPAD5},
            {"NUMPAD6",    (int) VirtualKeyCode.NUMPAD6},
            {"NUMPAD7",    (int) VirtualKeyCode.NUMPAD7},
            {"NUMPAD8",    (int) VirtualKeyCode.NUMPAD8},
            {"NUMPAD9",    (int) VirtualKeyCode.NUMPAD9},
            {"MULTIPLY",   (int) VirtualKeyCode.MULTIPLY},
            {"ADD",        (int) VirtualKeyCode.ADD},
            {"SEPARATOR",  (int) VirtualKeyCode.SEPARATOR},
            {"SUBTRACT",   (int) VirtualKeyCode.SUBTRACT},
            {"DECIMAL",    (int) VirtualKeyCode.DECIMAL},
            {"DIVIDE",     (int) VirtualKeyCode.DIVIDE},
            {"F1",         (int) VirtualKeyCode.F1},
            {"F2",         (int) VirtualKeyCode.F2},
            {"F3",         (int) VirtualKeyCode.F3},
            {"F4",         (int) VirtualKeyCode.F4},
            {"F5",         (int) VirtualKeyCode.F5},
            {"F6",         (int) VirtualKeyCode.F6},
            {"F7",         (int) VirtualKeyCode.F7},
            {"F8",         (int) VirtualKeyCode.F8},
            {"F9",         (int) VirtualKeyCode.F9},
            {"F10",        (int) VirtualKeyCode.F10},
            {"F11",        (int) VirtualKeyCode.F11},
            {"F12",        (int) VirtualKeyCode.F12},
            {"F13",        (int) VirtualKeyCode.F13},
            {"F14",        (int) VirtualKeyCode.F14},
            {"F15",        (int) VirtualKeyCode.F15},
            {"F16",        (int) VirtualKeyCode.F16},
            {"F17",        (int) VirtualKeyCode.F17},
            {"F18",        (int) VirtualKeyCode.F18},
            {"F19",        (int) VirtualKeyCode.F19},
            {"F20",        (int) VirtualKeyCode.F20},
            {"F21",        (int) VirtualKeyCode.F21},
            {"F22",        (int) VirtualKeyCode.F22},
            {"F23",        (int) VirtualKeyCode.F23},
            {"F24",        (int) VirtualKeyCode.F24},
            {"NUMLOCK",    (int) VirtualKeyCode.NUMLOCK},
            {"SCROLL",     (int) VirtualKeyCode.SCROLL},
            {"LSHIFT",     (int) VirtualKeyCode.LSHIFT},
            {"RSHIFT",     (int) VirtualKeyCode.RSHIFT},
            {"LCONTROL",   (int) VirtualKeyCode.LCONTROL},
            {"RCONTROL",   (int) VirtualKeyCode.RCONTROL},
            {"LMENU",      (int) VirtualKeyCode.LMENU},
            {"RMENU",      (int) VirtualKeyCode.RMENU},
            {"BROWSER_BACK",        (int) VirtualKeyCode.BROWSER_BACK},
            {"BROWSER_FORWARD",     (int) VirtualKeyCode.BROWSER_FORWARD},
            {"BROWSER_REFRESH",     (int) VirtualKeyCode.BROWSER_REFRESH},
            {"BROWSER_STOP",        (int) VirtualKeyCode.BROWSER_STOP},
            {"BROWSER_SEARCH",      (int) VirtualKeyCode.BROWSER_SEARCH},
            {"BROWSER_FAVORITES",   (int) VirtualKeyCode.BROWSER_FAVORITES},
            {"BROWSER_HOME",        (int) VirtualKeyCode.BROWSER_HOME},
            {"VOLUME_MUTE",         (int) VirtualKeyCode.VOLUME_MUTE},
            {"VOLUME_DOWN",         (int) VirtualKeyCode.VOLUME_DOWN},
            {"VOLUME_UP",           (int) VirtualKeyCode.VOLUME_UP},
            {"MEDIA_NEXT_TRACK",    (int) VirtualKeyCode.MEDIA_NEXT_TRACK},
            {"MEDIA_PREV_TRACK",    (int) VirtualKeyCode.MEDIA_PREV_TRACK},
            {"MEDIA_STOP",          (int) VirtualKeyCode.MEDIA_STOP},
            {"MEDIA_PLAY_PAUSE",    (int) VirtualKeyCode.MEDIA_PLAY_PAUSE},
            {"LAUNCH_MAIL",         (int) VirtualKeyCode.LAUNCH_MAIL},
            {"LAUNCH_MEDIA_SELECT", (int) VirtualKeyCode.LAUNCH_MEDIA_SELECT},
            {"LAUNCH_APP1",         (int) VirtualKeyCode.LAUNCH_APP1},
            {"LAUNCH_APP2",         (int) VirtualKeyCode.LAUNCH_APP2},
            {"OEM_1",               (int) VirtualKeyCode.OEM_1},
            {"OEM_PLUS",            (int) VirtualKeyCode.OEM_PLUS},
            {"OEM_COMMA",           (int) VirtualKeyCode.OEM_COMMA},
            {"OEM_MINUS",           (int) VirtualKeyCode.OEM_MINUS},
            {"OEM_PERIOD",          (int) VirtualKeyCode.OEM_PERIOD},
            {"OEM_2",               (int) VirtualKeyCode.OEM_2},
            {"OEM_3",               (int) VirtualKeyCode.OEM_3},
            {"OEM_4",               (int) VirtualKeyCode.OEM_4},
            {"OEM_5",               (int) VirtualKeyCode.OEM_5},
            {"OEM_6",               (int) VirtualKeyCode.OEM_6},
            {"OEM_7",               (int) VirtualKeyCode.OEM_7},
            {"OEM_8",               (int) VirtualKeyCode.OEM_8},
            {"OEM_102",             (int) VirtualKeyCode.OEM_102},
            {"PROCESSKEY",          (int) VirtualKeyCode.PROCESSKEY},
            {"PACKET",              (int) VirtualKeyCode.PACKET},
            {"ATTN",                (int) VirtualKeyCode.ATTN},
            {"CRSEL",               (int) VirtualKeyCode.CRSEL},
            {"EXSEL",               (int) VirtualKeyCode.EXSEL},
            {"EREOF",               (int) VirtualKeyCode.EREOF},
            {"PLAY",                (int) VirtualKeyCode.PLAY},
            {"ZOOM",                (int) VirtualKeyCode.ZOOM},
            {"NONAME",              (int) VirtualKeyCode.NONAME},
            {"PA1",                 (int) VirtualKeyCode.PA1},
            {"OEM_CLEAR",           (int) VirtualKeyCode.OEM_CLEAR},
            // 特殊キー
            {"V_KEY_NOTHING",       (int) CircleVirtualKey.V_KEY_NOTHING},
            {"V_KEY_FN",            (int) CircleVirtualKey.V_KEY_FN},
            {"V_KEY_UNE_BS",        (int) CircleVirtualKey.V_KEY_UNE_BS},
            {"V_KEY_IN_ENT",        (int) CircleVirtualKey.V_KEY_IN_ENT},
            {"V_KEY_IN_NE",         (int) CircleVirtualKey.V_KEY_IN_NE},
            {"V_KEY_SASS",          (int) CircleVirtualKey.V_KEY_SASS},
            {"V_KEY_FN_BS",         (int) CircleVirtualKey.V_KEY_FN_BS},
            {"V_KEY_PRES",          (int) CircleVirtualKey.V_KEY_PRES},
            // ホイール制御キー
            {"V_KEY_MOUSE_X",       (int) CircleVirtualKey.V_KEY_MOUSE_X},
            {"V_KEY_MOUSE_Y",       (int) CircleVirtualKey.V_KEY_MOUSE_Y},
            {"V_KEY_WHEEL_X",       (int) CircleVirtualKey.V_KEY_WHEEL_X},
            {"V_KEY_WHEEL_Y",       (int) CircleVirtualKey.V_KEY_WHEEL_Y},
            {"V_KEY_SHIFT_WHEEL_X", (int) CircleVirtualKey.V_KEY_SHIFT_WHEEL_X},
            {"V_KEY_SHIFT_WHEEL_Y", (int) CircleVirtualKey.V_KEY_SHIFT_WHEEL_Y},
            {"V_KEY_CTRL_WHEEL_X",  (int) CircleVirtualKey.V_KEY_CTRL_WHEEL_X},
            {"V_KEY_CTRL_WHEEL_Y",  (int) CircleVirtualKey.V_KEY_CTRL_WHEEL_Y},
            {"V_KEY_SC_WHEEL_X",    (int) CircleVirtualKey.V_KEY_SC_WHEEL_X},
            {"V_KEY_SC_WHEEL_Y",    (int) CircleVirtualKey.V_KEY_SC_WHEEL_Y},
            {"V_KEY_ALT_WHEEL_X",   (int) CircleVirtualKey.V_KEY_ALT_WHEEL_X},
            {"V_KEY_ALT_WHEEL_Y",   (int) CircleVirtualKey.V_KEY_ALT_WHEEL_Y},
            {"V_KEY_CIRCLE",        (int) CircleVirtualKey.V_KEY_CIRCLE}
        };

        public static int convNameToCode(string name)
        {
            if (!dict.ContainsKey(name)) throw (new System.Exception());
            return dict[name];
        }

        public static string convCodeToName(int code)
        {
            var pair = dict.FirstOrDefault(c => c.Value == (int)code);
            return pair.Key;
        }
    }
}
